name: weather_forecast_app
description: A new Flutter project.

# Prevent publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase & Auth
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0

  # State management
  provider: ^6.1.2

  # UI icons
  cupertino_icons: ^1.0.8
  sign_in_button: ^4.0.1

  # HTTP package
  http: ^1.6.0

  # Geolocation package
  geolocator: ^14.0.2

  # SQLite database
  sqflite: ^2.2.8+4
  path: ^1.8.3

  # Shared preferences
  shared_preferences: ^2.1.1
  firebase_messaging: ^16.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing utilities
  mocktail: ^1.0.3
  firebase_auth_mocks: ^0.15.1

  # Recommended lint rules
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png

